name: Status Functions

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check Formatting
      run: exit 0

    - name: Run Build
      run: exit 1

    - name: Run Tests
      run: exit 0

    # - name: Determine Status
    #   id: status
    #   if: always()
    #   run: |
    #     if ( ${{ job.status == 'failure' }} )
    #     {
    #         echo "status=failure" >> $GITHUB_OUTPUT
    #     }
    #     else if ( cancelled() )
    #     {
    #         echo "status=cancelled" >> $GITHUB_OUTPUT
    #     }
    #     else if ( success() )
    #     {
    #         echo "status=success" >> $GITHUB_OUTPUT
    #     }
    #     else {
    #         echo "status=unknown" >> $GITHUB_OUTPUT
    #     }

    - name: Output status
      if: always()
      run: echo "${{ job.status }}"